// src/modules/codegen/types.ts
// Contrato de entrada (JSON v2 del editor) y modelo intermedio Java
// del generador local de proyectos Spring Boot (Fase 1).

/** Atributo UML según contrato v2 (el frontend normaliza a vis|name|type). */
export interface UmlAttributeV2 {
  vis?: string
  visibility?: string
  name: string
  type?: string
}

/** Método UML según contrato v2. En esta fase no se traduce a código Java. */
export interface UmlMethodV2 {
  vis?: string
  visibility?: string
  name: string
  returnType?: string
}

/** Clase del diagrama (contrato v2). */
export interface UmlClassV2 {
  id: string
  x?: number
  y?: number
  w?: number
  h?: number
  name: string
  attributes?: UmlAttributeV2[]
  methods?: UmlMethodV2[]
}

/** Relación del diagrama (contrato v2). */
export interface UmlLinkV2 {
  id: string
  kind: string
  sourceId: string
  targetId: string
  labels?: { name?: string; src?: string; tgt?: string }
  assocClassId?: string
  anchorSrc?: unknown
  anchorTgt?: unknown
}

/** Diagrama JSON v2 completo ({ classes, links }). */
export interface DiagramV2 {
  classes: Record<string, UmlClassV2>
  links?: Record<string, UmlLinkV2>
}

/** Cuerpo del request de POST /api/codegen/spring-boot. */
export interface GenerateSpringBootRequest {
  projectName?: string
  includeDto?: boolean
  diagram?: DiagramV2
}

/** Request ya validado (valores saneados con defaults). */
export interface ValidatedGenerateRequest {
  projectName: string
  includeDto: boolean
  diagram: DiagramV2
}

/** Campo Java saneado y mapeado. */
export interface JavaField {
  /** Nombre de la variable en camelCase válido para Java. */
  name: string
  /** Tipo Java mapeado (String, Long, Integer, BigDecimal, LocalDate...). */
  javaType: string
  /** true si este campo es el identificador de la entidad. */
  isId: boolean
  /** true si el id se genera con @GeneratedValue(IDENTITY). */
  autoGeneratedId: boolean
}

/** Clase Java intermedia (desacoplada del generador de texto). */
export interface JavaClass {
  /** Nombre de la clase en PascalCase válido. */
  className: string
  /** Nombre de la superclase (extends X), si hay Generalization. */
  parentClassName?: string
  /** Nombre de tabla (y de ruta REST) en minúsculas. */
  tableName: string
  fields: JavaField[]
  /** true si otra clase la declara como padre (→ @Inheritance(JOINED)). */
  isParentWithSubclasses: boolean
}

/** Proyecto Java intermedio completo. */
export interface JavaProject {
  /** Nombre del proyecto entregado (p. ej. "demo-sources"). */
  projectName: string
  /** Slug del proyecto usado en artifact/package (p. ej. "demosources"). */
  slug: string
  /** Paquete base generado (p. ej. "com.example.demosources"). */
  basePackage: string
  /** Nombre de la clase @SpringBootApplication. */
  applicationClassName: string
  /** Carpeta raíz dentro del ZIP. */
  rootFolder: string
  classes: JavaClass[]
  includeDto: boolean
}